---
title: "Capstone-Project_Question02"
author: "Jazmine Snow"
date: "12/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)

library(dplyr)

library(dbplyr)
```

```{r}
# Created a new variable called "raw_data" that reads the csv file I created of the raw-data
raw_data <- read.csv("tumor-location_edited-data_csv.csv", as.is = TRUE) %>%
  print()
```

```{r}
# Changed the column names in the file to make them easier to work with
data_columns <- raw_data %>%
  rename(id = `ï..ID`, size_cm = `Size_Pathol_cm_`, subtype = `Subtype_1..ER.positive.3.triple.negative`, quadrants = `Qudrants2_1_UOQ_2_UIQ_3_LOQ_4_LIQ_5_periareolar_6___overlapping`, mr_location_ap = `MR_Location_AP__1__anterior_2__middle_3__posterior_`, mr_location_ml = `MR_Location_ML__1__medial_2__central_3__lateral_`, y_distance = `Y_distance`, x_norm = `X_normalized`, y_norm = `Y_normalized`, z_norm = `Z_normalized`, grade = `MG_grade`, x_distance = `X_distance`, z_distance = `Z_distance`, palpability = `Palpability`, histology = `Histologic_full`) %>%
  print()
```

```{r}
# Selected specific columns to look at for my question of interest and called it "data_selected"
data_selected <- data_columns %>%
  select(id, subtype, quadrants, mr_location_ml, mr_location_ap, x_distance, y_distance, z_distance, histology) %>%
# Filtered so that the dataframe only includes rows that have numerical data in the subtype column
  filter(!is.na(subtype)) %>%
  print()
```

Next, need to filter the data based on subtype. 1= ER positive data, 3= triple negative data

